"""create_fossils

Revision ID: 0f22240a1b2c
Revises: e2a325ea69b5
Create Date: 2025-11-23 22:57:47.919562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f22240a1b2c'
down_revision = 'e2a325ea69b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('tabular_data_set')
    #with op.batch_alter_table('data_set', schema=None) as batch_op:
        #batch_op.drop_column('ds_type')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_type', mysql.VARCHAR(length=50), nullable=False))

    op.create_table('tabular_data_set',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_set.id'], name=op.f('tabular_data_set_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
