"""empty message

Revision ID: 965ae65e2002
Revises: b757875a0cea
Create Date: 2025-12-07 21:31:23.349095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965ae65e2002'
down_revision = 'b757875a0cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hubfile_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hubfile_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_cart_item')
    # ### end Alembic commands ###
