"""fix_ds_metrics_columns

Revision ID: b757875a0cea
Revises: 1ee574bd9731
Create Date: 2025-11-24 10:11:56.649446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'b757875a0cea'
down_revision = '1ee574bd9731'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fossils_meta_data_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('author_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fossils_meta_data', ['fossils_meta_data_id'], ['id'])
        batch_op.drop_column('fm_meta_data_id')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fossils_file_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('file_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fossils_file', ['fossils_file_id'], ['id'])
        batch_op.drop_column('feature_model_id')
    '''
    if 'feature_model' in tables:
        op.drop_table('feature_model')
    if 'fm_metrics' in tables:
        op.drop_table('fm_meta_data')
    if 'fm_meta_data' in tables:
        op.drop_table('fm_metrics')
    
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_files', sa.String(length=120), nullable=True))
        batch_op.drop_column('number_of_models')
        batch_op.drop_column('number_of_features')

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('fossils_file_id')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_features', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('number_of_models', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('number_of_files')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('author_ibfk_2'), 'fm_meta_data', ['fm_meta_data_id'], ['id'])
        batch_op.drop_column('fossils_meta_data_id')

    op.create_table('fm_meta_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('publication_type', mysql.ENUM('NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER', 'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT', 'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT', 'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE', 'THESIS', 'WORKING_PAPER', 'OTHER'), nullable=False),
    sa.Column('publication_doi', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fm_metrics_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fm_metrics_id'], ['fm_metrics.id'], name='fm_meta_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_metrics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('solver', mysql.TEXT(), nullable=True),
    sa.Column('not_solver', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
