"""evolving_into_dinohub

Revision ID: cb9c6d6e4bf0
Revises: 0f22240a1b2c
Create Date: 2025-11-24 09:25:33.597910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect 

# revision identifiers, used by Alembic.
revision = 'cb9c6d6e4bf0'
down_revision = '0f22240a1b2c'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Obtenemos el inspector para ver qué hay en la base de datos
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    # 2. Creamos las tablas SOLO si no existen
    if 'fossils_meta_data' not in tables:
        op.create_table('fossils_meta_data',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('csv_filename', sa.String(length=120), nullable=False),
            sa.Column('title', sa.String(length=120), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('publication_doi', sa.String(length=120), nullable=True),
            sa.Column('tags', sa.String(length=120), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    if 'fossils_file' not in tables:
        op.create_table('fossils_file',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('data_set_id', sa.Integer(), nullable=False),
            sa.Column('fossils_meta_data_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
            sa.ForeignKeyConstraint(['fossils_meta_data_id'], ['fossils_meta_data.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # 3. Modificamos las tablas existentes (Author y File)
    # IMPORTANTE: Esto tiene que estar ANTES de borrar las tablas viejas
    with op.batch_alter_table('author', schema=None) as batch_op:
        # Nota: Si ya corriste esto parcialmente, podría dar error si la columna ya existe.
        # Si te da error aquí, avísame, pero normalmente batch_alter es más listo.
        batch_op.add_column(sa.Column('fossils_meta_data_id', sa.Integer(), nullable=True))
        # OJO: Verifica si necesitas borrar la constraint si ya se borró antes.
        # Por seguridad, puedes envolverlo en try/except o confiar en que Alembic maneje la idempotencia.
        try:
            batch_op.drop_constraint('author_ibfk_2', type_='foreignkey')
        except:
            pass
        
        batch_op.create_foreign_key(None, 'fossils_meta_data', ['fossils_meta_data_id'], ['id'])
        batch_op.drop_column('fm_meta_data_id')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fossils_file_id', sa.Integer(), nullable=False))
        try:
            batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        except:
            pass
        batch_op.create_foreign_key(None, 'fossils_file', ['fossils_file_id'], ['id'])
        batch_op.drop_column('feature_model_id')

    # 4. Borramos las tablas viejas (AL FINAL y en orden)
    # Verificamos si existen antes de borrar para evitar errores si ya se borraron parcialmente
    if 'feature_model' in tables:
        op.drop_table('feature_model')
        
    if 'fm_meta_data' in tables:
        op.drop_table('fm_meta_data')
        
    if 'fm_metrics' in tables:
        op.drop_table('fm_metrics')
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('fossils_file_id')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('author_ibfk_2'), 'fm_meta_data', ['fm_meta_data_id'], ['id'])
        batch_op.drop_column('fossils_meta_data_id')

    op.create_table('fm_meta_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('publication_type', mysql.ENUM('NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER', 'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT', 'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT', 'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE', 'THESIS', 'WORKING_PAPER', 'OTHER'), nullable=False),
    sa.Column('publication_doi', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fm_metrics_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fm_metrics_id'], ['fm_metrics.id'], name='fm_meta_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_metrics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('solver', mysql.TEXT(), nullable=True),
    sa.Column('not_solver', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fossils_file')
    op.drop_table('fossils_meta_data')
    # ### end Alembic commands ###